In [1]:
!pip -q install feast==0.64.0 pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 25.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 17.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 19.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 52.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 61.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.9/531.9 kB 41.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 2.4.0 requires tenacity<10,>=9, but you have tenacity 8.5.0 which is incompatible.

In [2]:
import feast

print("Feast version:", feast.__version__)

Feast version: 0.64.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [3]:
from google.colab import files

uploaded = files.upload()

Saving skill_gap.csv to skill_gap (1).csv

In [4]:
import pandas as pd

df = pd.read_csv("/content/skill_gap.csv")

print(df.head())
print(df.shape)

  student_id  python  java  sql  dsa  machine_learning  cloud  \
0       S001       9     8    8    5                 6      8
1       S002       6     9    3    4                 5      8
2       S003       7     6    7    5                 6      7
3       S004       9     3    8    9                 9      4
4       S005       5     8    6    5                 4      2

   web_development  communication  problem_solving  skill_gap_score  placement
0                7              5                4             3.33          0
1                9              4                6             4.00          0
2                3              9                8             3.56          0
3                8              8                4             3.11          0
4                8              7                6             4.33          0
(100, 12)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [5]:
print(df.columns)
print(df.info())
print(df.isnull().sum())

Index(['student_id', 'python', 'java', 'sql', 'dsa', 'machine_learning',
       'cloud', 'web_development', 'communication', 'problem_solving',
       'skill_gap_score', 'placement'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   student_id        100 non-null    object
 1   python            100 non-null    int64
 2   java              100 non-null    int64
 3   sql               100 non-null    int64
 4   dsa               100 non-null    int64
 5   machine_learning  100 non-null    int64
 6   cloud             100 non-null    int64
 7   web_development   100 non-null    int64
 8   communication     100 non-null    int64
 9   problem_solving   100 non-null    int64
 10  skill_gap_score   100 non-null    float64
 11  placement         100 non-null    int64
dtypes: float64(1), int64(10), object(1)
memory usage: 9.5+ KB
None
student_id          0
python              0
java                0
sql                 0
dsa                 0
machine_learning    0
cloud               0
web_development     0
communication       0
problem_solving     0
skill_gap_score     0
placement           0
dtype: int64

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [6]:
import pandas as pd
df = pd.read_csv("/content/skill_gap.csv")
technical_cols = [
    "python",
    "java",
    "sql",
    "dsa",
    "machine_learning",
    "cloud",
    "web_development"
]
df["technical_skill_score"] = df[technical_cols].mean(axis=1)
soft_cols = ["communication", "problem_solving"]

df["soft_skill_score"] = df[soft_cols].mean(axis=1)
df["strong_skill_count"] = (
    df[technical_cols + soft_cols] >= 7
).sum(axis=1)
df["weak_skill_count"] = (
    df[technical_cols + soft_cols] < 5
).sum(axis=1)
df["overall_skill_score"] = (
    df["technical_skill_score"] * 0.7 +
    df["soft_skill_score"] * 0.3
)
print(df.head())
df.to_csv("skill_gap_features.csv", index=False)
print("Feature extraction completed successfully!")

  student_id  python  java  sql  dsa  machine_learning  cloud  \
0       S001       9     8    8    5                 6      8
1       S002       6     9    3    4                 5      8
2       S003       7     6    7    5                 6      7
3       S004       9     3    8    9                 9      4
4       S005       5     8    6    5                 4      2

   web_development  communication  problem_solving  skill_gap_score  \
0                7              5                4             3.33
1                9              4                6             4.00
2                3              9                8             3.56
3                8              8                4             3.11
4                8              7                6             4.33

   placement  technical_skill_score  soft_skill_score  strong_skill_count  \
0          0               7.285714               4.5                   5
1          0               6.285714               5.0                   3
2          0               5.857143               8.5                   5
3          0               7.142857               6.0                   6
4          0               5.428571               6.5                   3

   weak_skill_count  overall_skill_score
0                 1                 6.45
1                 3                 5.90
2                 1                 6.65
3                 3                 6.80
4                 2                 5.75
Feature extraction completed successfully!

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [7]:
df[
    [
        "student_id",
        "python",
        "java",
        "sql",
        "dsa",
        "machine_learning",
        "cloud",
        "web_development",
        "communication",
        "problem_solving",
        "technical_skill_score",
        "soft_skill_score",
        "strong_skill_count",
        "weak_skill_count",
        "overall_skill_score",
        "skill_gap_score",
        "placement"
    ]
].head()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,python,java,sql,dsa,machine_learning,cloud,web_development,communication,problem_solving,technical_skill_score,soft_skill_score,strong_skill_count,weak_skill_count,overall_skill_score,skill_gap_score,placement
0,S001,9,8,8,5,6,8,7,5,4,7.285714,4.5,5,1,6.45,3.33,0
1,S002,6,9,3,4,5,8,9,4,6,6.285714,5.0,3,3,5.90,4.00,0
2,S003,7,6,7,5,6,7,3,9,8,5.857143,8.5,5,1,6.65,3.56,0
3,S004,9,3,8,9,9,4,8,8,4,7.142857,6.0,6,3,6.80,3.11,0
4,S005,5,8,6,5,4,2,8,7,6,5.428571,6.5,3,2,5.75,4.33,0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [8]:
base_time = pd.Timestamp(
    "2024-01-01",
    tz="UTC"
)
df["event_timestamp"] = (
    base_time +
    pd.to_timedelta(
        df["student_id"].str.extract(r'(\d+)')[0].astype(int),
        unit="s"
    )
)
df["created_timestamp"] = (
    df["event_timestamp"] +
    pd.Timedelta(seconds=1)
)
df[
    [
        "student_id",
        "event_timestamp",
        "created_timestamp"
    ]
].head()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

  student_id           event_timestamp         created_timestamp
0       S001 2024-01-01 00:00:01+00:00 2024-01-01 00:00:02+00:00
1       S002 2024-01-01 00:00:02+00:00 2024-01-01 00:00:03+00:00
2       S003 2024-01-01 00:00:03+00:00 2024-01-01 00:00:04+00:00
3       S004 2024-01-01 00:00:04+00:00 2024-01-01 00:00:05+00:00
4       S005 2024-01-01 00:00:05+00:00 2024-01-01 00:00:06+00:00

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [9]:
feature_df = df[
    [
        "student_id",
        "event_timestamp",
        "created_timestamp",
        "python",
        "java",
        "sql",
        "dsa",
        "machine_learning",
        "cloud",
        "web_development",
        "communication",
        "problem_solving",
        "technical_skill_score",
        "soft_skill_score",
        "strong_skill_count",
        "weak_skill_count",
        "overall_skill_score"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [10]:
label_df = df[
    [
        "student_id",
        "event_timestamp",
        "placement"
    ]
].copy()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [11]:
print("Feature data:")
display(feature_df.head())

print("Labels:")
display(label_df.head())

Feature data:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,student_id,event_timestamp,created_timestamp,python,java,sql,dsa,machine_learning,cloud,web_development,communication,problem_solving,technical_skill_score,soft_skill_score,strong_skill_count,weak_skill_count,overall_skill_score
0,S001,2024-01-01 00:00:01+00:00,2024-01-01 00:00:02+00:00,9,8,8,5,6,8,7,5,4,7.285714,4.5,5,1,6.45
1,S002,2024-01-01 00:00:02+00:00,2024-01-01 00:00:03+00:00,6,9,3,4,5,8,9,4,6,6.285714,5.0,3,3,5.90
2,S003,2024-01-01 00:00:03+00:00,2024-01-01 00:00:04+00:00,7,6,7,5,6,7,3,9,8,5.857143,8.5,5,1,6.65
3,S004,2024-01-01 00:00:04+00:00,2024-01-01 00:00:05+00:00,9,3,8,9,9,4,8,8,4,7.142857,6.0,6,3,6.80
4,S005,2024-01-01 00:00:05+00:00,2024-01-01 00:00:06+00:00,5,8,6,5,4,2,8,7,6,5.428571,6.5,3,2,5.75

Labels:

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

  student_id           event_timestamp  placement
0       S001 2024-01-01 00:00:01+00:00          0
1       S002 2024-01-01 00:00:02+00:00          0
2       S003 2024-01-01 00:00:03+00:00          0
3       S004 2024-01-01 00:00:04+00:00          0
4       S005 2024-01-01 00:00:05+00:00          0

In [12]:
import os

repo_path = "/content/skill_gap_feast"

os.makedirs(
    f"{repo_path}/data",
    exist_ok=True
)

In [13]:
feature_df.to_parquet(
    f"{repo_path}/data/skill_gap_features.parquet",
    index=False
)

In [14]:
feature_store_yaml = """
project: skill_gap_project

registry: data/registry.db

provider: local

offline_store:
  type: file

online_store:
  type: sqlite
  path: data/online_store.db
"""

with open(
    f"{repo_path}/feature_store.yaml",
    "w"
) as f:
    f.write(feature_store_yaml)

In [15]:
feature_definition = '''
from datetime import timedelta

from feast import (
    Entity,
    FeatureView,
    FeatureService,
    Field,
    FileSource
)

from feast.types import (
    Float32,
    Int64
)


# -----------------------------
# ENTITY
# -----------------------------

student = Entity(
    name="student",
    join_keys=["student_id"],
    description="Student in the curriculum-industry skill-gap dataset"
)


# -----------------------------
# DATA SOURCE
# -----------------------------

skill_gap_source = FileSource(
    name="skill_gap_source",
    path="data/skill_gap_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp"
)


# -----------------------------
# FEATURE VIEW
# -----------------------------

skill_gap_feature_view = FeatureView(
    name="skill_gap_features",
    entities=[student],

    ttl=timedelta(days=50000),

    schema=[
        Field(
            name="technical_skill_score",
            dtype=Float32
        ),

        Field(
            name="soft_skill_score",
            dtype=Float32
        ),

        Field(
            name="strong_skill_count",
            dtype=Int64
        ),

        Field(
            name="weak_skill_count",
            dtype=Int64
        ),

        Field(
            name="overall_skill_score",
            dtype=Float32
        ),
    ],

    source=skill_gap_source,

    online=True
)


# -----------------------------
# FEATURE SERVICE
# -----------------------------

skill_gap_feature_service = FeatureService(
    name="skill_gap_service",
    features=[
        skill_gap_feature_view
    ]
)
'''

with open(
    f"{repo_path}/features.py",
    "w"
) as f:
    f.write(feature_definition)

print("features.py created successfully!")

features.py created successfully!

In [16]:
!find /content/skill_gap_feast -maxdepth 2 -type f

/content/skill_gap_feast/features.py
/content/skill_gap_feast/data/skill_gap_features.parquet
/content/skill_gap_feast/feature_store.yaml

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [19]:
%cd /content/skill_gap_feast

/content/skill_gap_feast

In [20]:
!feast apply

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
/content/skill_gap_feast/features.py:22: DeprecationWarning: Entity value_type will be mandatory in the next release. Please specify a value_type for entity 'student'.
  student = Entity(
No project found in the repository. Using project name skill_gap_project defined in feature_store.yaml
Applying changes for project skill_gap_project
Created project skill_gap_project
Created entity student
Created feature view skill_gap_features
Created feature service skill_gap_service

Created sqlite table skill_gap_project_skill_gap_features

In [21]:
!feast entities list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME     DESCRIPTION                                           TYPE
student  Student in the curriculum-industry skill-gap dataset  ValueType.UNKNOWN

In [22]:
!feast feature-views list

/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
NAME                ENTITIES     TYPE         ENABLED    STATE
skill_gap_features  {'student'}  FeatureView  Yes        STATE_UNSPECIFIED

In [23]:
from feast import FeatureStore

store = FeatureStore(
    repo_path="/content/skill_gap_feast"
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [24]:
feature_service = store.get_feature_service(
    "skill_gap_service"
)

In [25]:
entity_df = label_df.copy()

display(entity_df.head())

  student_id           event_timestamp  placement
0       S001 2024-01-01 00:00:01+00:00          0
1       S002 2024-01-01 00:00:02+00:00          0
2       S003 2024-01-01 00:00:03+00:00          0
3       S004 2024-01-01 00:00:04+00:00          0
4       S005 2024-01-01 00:00:05+00:00          0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [26]:
training_data = store.get_historical_features(
    entity_df=entity_df,
    features=feature_service
).to_df()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [27]:
display(training_data.head())

,student_id,event_timestamp,placement,technical_skill_score,soft_skill_score,strong_skill_count,weak_skill_count,overall_skill_score
0,S001,2024-01-01 00:00:01+00:00,0,7.285714,4.5,5,1,6.45
1,S002,2024-01-01 00:00:02+00:00,0,6.285714,5.0,3,3,5.90
2,S003,2024-01-01 00:00:03+00:00,0,5.857143,8.5,5,1,6.65
3,S004,2024-01-01 00:00:04+00:00,0,7.142857,6.0,6,3,6.80
4,S005,2024-01-01 00:00:05+00:00,0,5.428571,6.5,3,2,5.75

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [28]:
feature_columns = [
    "python",
    "java",
    "sql",
    "dsa",
    "machine_learning",
    "cloud",
    "web_development",
    "communication",
    "problem_solving",
    "industry_skill_score",
    "skill_gap_score",
    "industry_readiness_score",
    "average_skill_score",
    "strong_skill_count",
    "weak_skill_count",
    "technical_skill_score"
]

In [29]:
feature_columns = [
    "technical_skill_score",
    "soft_skill_score",
    "strong_skill_count",
    "weak_skill_count",
    "overall_skill_score"
]

X = training_data[feature_columns]

y = training_data["placement"]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [31]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

model.fit(
    X_train,
    y_train
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [32]:
predictions = model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [33]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    predictions
)

print(
    "Accuracy:",
    round(accuracy * 100, 2),
    "%"
)

Accuracy: 85.0 %

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [34]:
%cd /content/skill_gap_feast

!feast materialize \
    2026-01-01T00:00:00 \
    2026-01-02T00:00:00

/content/skill_gap_feast
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:64: PyparsingDeprecationWarning: 'oneOf' deprecated - use 'one_of'
  prop = Group((name + Suppress("=") + comma_separated(value)) | oneOf(_CONSTANTS))
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:85: PyparsingDeprecationWarning: 'parseString' deprecated - use 'parse_string'
  parse = parser.parseString(pattern)
/usr/local/lib/python3.12/dist-packages/matplotlib/_fontconfig_pattern.py:89: PyparsingDeprecationWarning: 'resetCache' deprecated - use 'reset_cache'
  parser.resetCache()
/usr/local/lib/python3.12/dist-packages/matplotlib/_mathtext.py:45: PyparsingDeprecationWarning: 'enablePackrat' deprecated - use 'enable_packrat'
  ParserElement.enablePackrat()
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'parseString' deprecated - use 'parse_string'
In /usr/local/lib/python3.12/dist-packages/matplotlib/mpl-data/stylelib/classic.mplstyle: 'resetCache' deprecated - use 'reset_cache'
Materializing 1 feature views from 2026-01-01 00:00:00+00:00 to 2026-01-02 00:00:00+00:00 into the sqlite online store.

skill_gap_features:

In [35]:
online_features = store.get_online_features(
    features=feature_service,
    entity_rows=[
        {
            "student_id": "S025"
        }
    ]
).to_dict()

In [36]:
print(online_features)

{'student_id': ['S025'], 'strong_skill_count': [None], 'overall_skill_score': [None], 'technical_skill_score': [None], 'soft_skill_score': [None], 'weak_skill_count': [None]}

In [37]:
online_df = pd.DataFrame(
    online_features
)

display(online_df)

,student_id,strong_skill_count,overall_skill_score,technical_skill_score,soft_skill_score,weak_skill_count
0,S025,None,None,None,None,None

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [38]:
final_model = DecisionTreeClassifier(
    max_depth=4,
    random_state=42
)

final_model.fit(X, y)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [39]:
X_online = online_df[
    feature_columns
]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [40]:
prediction = final_model.predict(
    X_online
)

print(
    "Predicted placement:",
    prediction[0]
)

Predicted placement: 0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [41]:
online_features = store.get_online_features(
    features=feature_service,
    entity_rows=[
        {"student_id": "S010"},
        {"student_id": "S020"},
        {"student_id": "S030"},
        {"student_id": "S040"}
    ]
).to_dict()

online_df = pd.DataFrame(
    online_features
)

display(online_df)

,student_id,strong_skill_count,overall_skill_score,technical_skill_score,soft_skill_score,weak_skill_count
0,S010,None,None,None,None,None
1,S020,None,None,None,None,None
2,S030,None,None,None,None,None
3,S040,None,None,None,None,None

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [42]:
online_df["predicted_placement"] = (
    final_model.predict(
        online_df[feature_columns]
    )
)

display(
    online_df[
        [
            "student_id",
            "predicted_placement"
        ]
    ]
)

  student_id  predicted_placement
0       S010                    0
1       S020                    0
2       S030                    0
3       S040                    0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)